import { faker } from "..";
/**
 * Represents a user with basic details for registration.
 */
export interface User {
  /** The user's username, typically generated as a combination of their first and last name. */
  username: string;

  /** The user's email address. */
  email: string;

  /** The user's first name. */
  firstName: string;

  /** The user's last name. */
  lastName: string;

  /** The user's password. */
  password: string;
}

/**
 * - Generates a random user with a username, email, first name, last name, and password.
 *
 * - The username is generated by concatenating the lowercase first and last name, separated by a period.
 * 
 * - The password is currently set to a static value ("password123").
 * 
 * Static password for demonstration purposes
 * 
 * @returns {User} A randomly generated user object.
 */
export function generateRandomUser(): User {
  const firstName = faker.person.firstName();
  const lastName = faker.person.lastName();

  return {
    username: `${firstName.toLowerCase()}.${lastName.toLowerCase()}`, // Username is generated based on firstName and lastName
    firstName,
    lastName,
    email: `${firstName}.${lastName}@example.com`,
    password: "password123"
  };
};